CREATE DATABASE skatepark;
CREATE TABLE skaters (id SERIAL, email VARCHAR(100) NOT NULL, nombre
VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL, anos_experiencia
INT NOT NULL, especialidad VARCHAR(100) NOT NULL, foto VARCHAR(255) NOT
NULL, estado BOOLEAN NOT NULL);
